# -*- coding: utf-8 -*-

# Table of letters
A = ".-"
B = "-..."
C = "-.-."
D = "-.."
E = "."
F = "..-."
G = "--."
H = "...."
I = ".."
J = ".---"
K = "-.-"
L = ".-.."
M = "--"
N = "-."
O = "---"
P = ".--."
Q = "--.-"
R = ".-."
S = "..."
T = "-"
U = "..-"
V = "...-"
W = ".--"
X = "-..-"
Y = "-.--"
Z = "--.."

# Table of numbers
zero = "-----"
one = ".----"
two = "..---"
three = "...--"
four = "....-"
five = "....."
six = "-...."
seven = "--..."
height = "---.."
nine = "----."

# Table of punctuations
point = ".-.-.-"
comma = "--..--"
questionMark = "..--.."
minus = "-....-"
equal = "-...-"
colon = "---..."
semicolon = "-.-.-."
parentheseLeft = "-.--."
parentheseRight = "-.--.-"
slash = "-..-."
quotationMark = ".-..-."
dollar = "...-..-"
apostrophe = ".----."
dash = "..--.-"
atSign = ".--.-."
exclamationMark = "---."
plus = ".-.-."
tilde = ".-..."
hashtag = "...-.-"
ampersand = ". ..."
